In [1]:

from policies.gaussian_mlp_policy import GaussianMLPPolicy
from garage.envs import GymEnv
import torch

env = GymEnv('Pendulum-v0')
policy = GaussianMLPPolicy(env.spec,
                           hidden_sizes=[32, 32],
                           hidden_nonlinearity=torch.tanh,
                           output_nonlinearity=None)

In [2]:
observation, _ = env.reset()

In [3]:
policy.get_action(observation)

(array([0.4195063], dtype=float32),
 {'mean': array([-0.4664911], dtype=float32),
  'log_std': array([0.], dtype=float32)})

In [4]:
policy.reset()

In [5]:
policy.get_action(observation)

(array([0.3697005], dtype=float32),
 {'mean': array([-0.4664911], dtype=float32),
  'log_std': array([0.], dtype=float32)})

In [6]:
policy.get_param_values()

tensor([ 0.0000,  0.0163, -0.1440,  ..., -0.1966, -0.3103,  0.0000],
       grad_fn=<CatBackward>)